name: Terraform Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform-format:
    name: Terraform Format Check
    if: github.base_ref == github.event.repository.default_branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Format Check
        id: fmt
        run: |
          UNFORMATTED_FILES=$(terraform fmt -check -recursive -diff 2>&1 | grep -E '.*\.tf$' || true)

          if [[ -z "$UNFORMATTED_FILES" ]]; then
            echo "formatted=true" >> "$GITHUB_ENV"
          else
            echo "formatted=false" >> "$GITHUB_ENV"
            echo "❌ The following Terraform files are not formatted:"
            echo "$UNFORMATTED_FILES"
            exit 1
          fi

      - name: Output Format Status
        run: |
          echo "Terraform Format Status: ${{ env.formatted }}"
